name: Check Tests Pass

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm@9.12.0

      - name: Install dependencies
        run: pnpm install
        working-directory: library

      - name: Run tests
        run: pnpm test
        working-directory: library
